### ISSUE TITLE
Hello can you do a 1vs1?

### ISSUE THREAD

**Issue by Papadoubulus** [ProgStudy/VoteKickOrBan#1]
Hello can you do a 1vs1?

**Comment by dev-null-user** [comment]
> Hello can you do a 1vs1?

Hello, write specifically what do you mean, how should this work approximately?

**Comment by Papadoubulus** [comment]
1vs1 the player should have iron armor and iron sword and for example if I hit you in the lobby with a sword and you also me that we 2 will be teleported in a free round

**Comment by Papadoubulus** [comment]
sorry for my english i am german

**Comment by dev-null-user** [comment]
> sorry for my english i am german

Everything is fine :), I rephrase, if one of the two players hits the other, then they teleport back (for example, to spawn) and the one who hit the first becomes the winner

Did I understand you correctly?

**Comment by Papadoubulus** [comment]
if I hit him with the sword and he hits me back then they go into 1vs1 with armor and therefore swords into a duel who dies has lost

**Comment by Papadoubulus** [comment]
one vs one

**Comment by dev-null-user** [comment]
> if I hit him with the sword and he hits me back then they go into 1vs1 with armor and therefore swords into a duel who dies has lost

Ok, this can be implemented. As there will be free time, I will write a plugin!

**Comment by Papadoubulus** [comment]
Thanks
