### ISSUE TITLE
reproduce plugin

### ISSUE THREAD

**Issue by ghost** [ProgStudy/VoteKickOrBan#2]
Hi author!
The plugin is great，could I reproduce the plugin to mcbbs? I marked you as the author in the MCBBS，Users download the plugin in your original Nukkitx forum

**Comment by dev-null-user** [comment]
> Hi author!
> The plugin is great，could I reproduce the plugin to mcbbs? I marked you as the author in the MCBBS，Users download the plugin in your original Nukkitx forum

Hi, It is allowed :)
